// Generated by CoffeeScript 1.6.3
(function() {
  (function($, window, document) {
    var Console;
    $.prototype.console = function($options) {
      var _ref;
      if ($options == null) {
        $options = {};
      }
      return (_ref = $.data(this, 'console')) != null ? _ref : $.data(this, 'console', new Console(this, $options));
    };
    return Console = (function() {
      var KEY_BS, KEY_C, KEY_CR, KEY_DOWN, KEY_ESC, KEY_R, KEY_S, KEY_TAB, KEY_UP, fix;

      KEY_BS = 8;

      KEY_TAB = 9;

      KEY_CR = 13;

      KEY_ESC = 27;

      KEY_UP = 38;

      KEY_DOWN = 40;

      KEY_C = 67;

      KEY_R = 82;

      KEY_S = 83;

      fix = function($text) {
        return $text.replace(/\ /g, "&nbsp;").replace(/\n/g, "<br />");
      };

      Console.prototype.histpos = 0;

      Console.prototype.history = null;

      Console.prototype.kb = null;

      Console.prototype.output = null;

      Console.prototype.prompt = null;

      Console.prototype["default"] = {
        autofocus: true,
        history: true,
        welcome: '',
        prompt: '> ',
        promptAlt: '? ',
        commandHandle: function() {},
        cancelHandle: function() {}
      };

      function Console($container, $options) {
        var $auto, $this;
        $this = this;
        $this.history = [];
        this.options = $options = $.extend(this["default"], $options);
        $auto = $options.autofocus ? 'autofocus' : '';
        $container.html("<output></output>\n<div id=\"input-line\" class=\"input-line\">\n<div class=\"prompt\"></div><div><input class=\"cmdline\" " + $auto + " /></div>\n</div>");
        this.output = $container.find('output');
        this.prompt = $container.find('#input-line .prompt');
        this.kb = $container.find('#input-line .cmdline');
        this.prompt.text($options.prompt);
        this.print("<div>" + $options.welcome + "</div>");
        $(window).on('click', function($e) {
          return $this.kb.focus();
        });
        $(document.body).on('keydown', function($e) {
          if ($e.keyCode === KEY_ESC) {
            $e.stopPropagation();
            return $e.preventDefault();
          }
        });
        this.kb.on('click', function($e) {
          return this.value = this.value;
        });
        this.kb.on('keyup', function($e) {
          var $temp;
          if (!$options.history) {
            return;
          }
          $temp = 0;
          if ($this.history.length) {
            if ($e.keyCode === KEY_UP || $e.keyCode === KEY_DOWN) {
              if ($this.history[$this.histpos]) {
                $this.history[$this.histpos] = this.value;
              } else {
                $temp = this.value;
              }
            }
            if ($e.keyCode === KEY_UP) {
              $this.histpos--;
              if ($this.histpos < 0) {
                $this.histpos = 0;
              }
            } else if ($e.keyCode === KEY_DOWN) {
              $this.histpos++;
              if ($this.histpos > $this.history.length) {
                $this.histpos = $this.history.length;
              }
            }
            if ($e.keyCode === KEY_UP || $e.keyCode === KEY_DOWN) {
              this.value = $this.history[$this.histpos] ? $this.history[$this.histpos] : $temp;
              return this.value = this.value;
            }
          }
        });
        this.kb.on('keydown', function($e) {
          if ($e.ctrlKey || $e.metaKey) {
            switch ($e.keyCode) {
              case KEY_C:
                $options.cancelHandle();
                $e.preventDefault();
                return $e.stopPropagation();
              case KEY_R:
                $this.clear(this);
                $e.preventDefault();
                return $e.stopPropagation();
              case KEY_S:
                $container.toggleClass('flicker');
                $e.preventDefault();
                return $e.stopPropagation();
            }
          }
        });
        this.kb.on('keydown', function($e) {
          var $input, $line;
          switch ($e.keyCode) {
            case KEY_BS:
              if (!this.value) {

              }
              break;
            case KEY_TAB:
              return $e.preventDefault;
            case KEY_CR:
              if (this.value) {
                $this.history[$this.history.length] = this.value;
                $this.histpos = $this.history.length;
              }
              $line = this.parentNode.parentNode.cloneNode(true);
              $line.removeAttribute('id');
              $line.classList.add('line');
              $input = $line.querySelector('input.cmdline');
              $input.autofocus = false;
              $input.readOnly = true;
              $this.output.append($line);
              $this.kb.get(0).scrollIntoView();
              if (this.value && this.value.trim()) {
                $options.commandHandle(this.value);
              }
              return this.value = '';
          }
        });
      }

      Console.prototype.clear = function($input) {
        this.output.html('');
        return $input != null ? $input.value = '' : void 0;
      };

      Console.prototype.setPrompt = function($prompt) {
        if ($prompt == null) {
          $prompt = false;
        }
        return this.prompt.text($prompt ? this.options.promptAlt : this.options.prompt);
      };

      Console.prototype.print = function($text) {
        if ($text == null) {
          $text = '';
        }
        this.output.append(fix($text));
        return this.kb.get(0).scrollIntoView();
      };

      Console.prototype.println = function($text) {
        if ($text == null) {
          $text = '';
        }
        this.output.append(fix("" + $text + "\n"));
        return this.kb.get(0).scrollIntoView();
      };

      Console.prototype.debug = function($text) {
        this.output.append("<span style=\"color: blue;\">" + fix("" + $text + "\n") + "</span>");
        return this.kb.get(0).scrollIntoView();
      };

      Console.prototype.highlight = function($text) {
        this.output.append("<span style=\"color: yellow;\">" + fix("" + $text + "\n") + "</span>");
        return this.kb.get(0).scrollIntoView();
      };

      return Console;

    })();
  })(jQuery, window, document);

}).call(this);
